import type { DisabilityType } from '@/types/profile'

export interface Destination {
  id: string
  name: string
  country: string
  flag: string
  bgColor: string
  accessibilityRating: number // 1-5
  disabilityTypes: DisabilityType[] // which needs are well covered
  featuresES: string[]
  featuresEN: string[]
  descriptionES: string
  descriptionEN: string
  tags: string[]
}

export const DESTINATIONS: Destination[] = [
  {
    id: 'puerto-rico',
    name: 'San Juan',
    country: 'Puerto Rico',
    flag: '🇵🇷',
    bgColor: 'bg-blue-400',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva'],
    featuresES: ['Playas con sillas anfibias', 'Hoteles certificados ADA', 'Transporte adaptado', 'Señalización en braille', 'Guías en lengua de señas'],
    featuresEN: ['Beaches with amphibious chairs', 'ADA-certified hotels', 'Adapted transport', 'Braille signage', 'Sign language guides'],
    descriptionES: 'San Juan es uno de los destinos más accesibles del Caribe, con infraestructura ADA en hoteles, playas adaptadas y transporte público accesible.',
    descriptionEN: 'San Juan is one of the most accessible destinations in the Caribbean, with ADA infrastructure in hotels, adapted beaches, and accessible public transport.',
    tags: ['caribe', 'playa', 'cultura'],
  },
  {
    id: 'cancun',
    name: 'Cancún',
    country: 'México',
    flag: '🇲🇽',
    bgColor: 'bg-cyan-400',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual'],
    featuresES: ['Zona Hotelera con accesos adaptados', 'Playas accesibles en El Garrafón', 'Hoteles all-inclusive con sillas de ruedas', 'Rampas en zona arqueológica Tulum', 'Transporte turístico adaptado'],
    featuresEN: ['Hotel Zone with adapted access', 'Accessible beaches at El Garrafón', 'All-inclusive hotels with wheelchairs', 'Ramps at Tulum archaeological zone', 'Adapted tourist transport'],
    descriptionES: 'Cancún ofrece una zona hotelera con amplia infraestructura accesible, playas adaptadas y tours accesibles a zonas arqueológicas cercanas.',
    descriptionEN: 'Cancún offers a hotel zone with extensive accessible infrastructure, adapted beaches, and accessible tours to nearby archaeological sites.',
    tags: ['caribe', 'playa', 'naturaleza'],
  },
  {
    id: 'cartagena',
    name: 'Cartagena',
    country: 'Colombia',
    flag: '🇨🇴',
    bgColor: 'bg-yellow-400',
    accessibilityRating: 3,
    disabilityTypes: ['motriz', 'auditiva'],
    featuresES: ['Ciudad amurallada con rutas adaptadas', 'Hoteles boutique accesibles en el centro', 'Playas accesibles en Bocagrande', 'Audioguías disponibles', 'Carros de golf adaptados para tours'],
    featuresEN: ['Walled city with adapted routes', 'Accessible boutique hotels downtown', 'Accessible beaches in Bocagrande', 'Audio guides available', 'Adapted golf carts for tours'],
    descriptionES: 'Cartagena combina historia colonial con infraestructura accesible creciente. El centro histórico tiene rutas adaptadas y transporte en carros de golf.',
    descriptionEN: 'Cartagena combines colonial history with growing accessible infrastructure. The historic center has adapted routes and golf cart transport.',
    tags: ['cultura', 'historia', 'caribe'],
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    bgColor: 'bg-sky-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva'],
    featuresES: ['Metro con plataformas elevadoras', 'Museos con recorridos táctiles', 'Teatro Colón accesible', 'Semáforos con señal sonora', 'Guías en lengua de señas argentina (LSA)', 'Mapas en braille'],
    featuresEN: ['Subway with elevating platforms', 'Museums with tactile tours', 'Accessible Teatro Colón', 'Traffic lights with audio signals', 'Argentine sign language (LSA) guides', 'Braille maps'],
    descriptionES: 'Buenos Aires tiene una de las infraestructuras de accesibilidad más desarrolladas de LATAM, con metro adaptado, museos inclusivos y amplia red de apoyo.',
    descriptionEN: 'Buenos Aires has one of the most developed accessibility infrastructures in LATAM, with adapted subway, inclusive museums, and extensive support network.',
    tags: ['cultura', 'ciudad', 'gastronomia'],
  },
  {
    id: 'cdmx',
    name: 'Ciudad de México',
    country: 'México',
    flag: '🇲🇽',
    bgColor: 'bg-green-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'auditiva'],
    featuresES: ['Metro con módulos de accesibilidad', 'Museos con lenguaje de señas mexicano (LSM)', 'Paseo de la Reforma con rampas', 'TURIBUS accesible', 'Zonas arqueológicas con recorridos adaptados', 'Braille en museos INAH'],
    featuresEN: ['Subway with accessibility modules', 'Museums with Mexican sign language (LSM)', 'Paseo de la Reforma with ramps', 'Accessible TURIBUS', 'Archaeological zones with adapted tours', 'Braille in INAH museums'],
    descriptionES: 'La CDMX cuenta con infraestructura de accesibilidad en transporte público, museos de clase mundial con programas inclusivos y tours adaptados.',
    descriptionEN: 'Mexico City has accessibility infrastructure in public transport, world-class museums with inclusive programs, and adapted tours.',
    tags: ['cultura', 'ciudad', 'historia', 'gastronomia'],
  },
  {
    id: 'punta-cana',
    name: 'Punta Cana',
    country: 'República Dominicana',
    flag: '🇩🇴',
    bgColor: 'bg-amber-400',
    accessibilityRating: 3,
    disabilityTypes: ['motriz'],
    featuresES: ['Resorts all-inclusive adaptados', 'Sillas anfibias en resorts premium', 'Habitaciones accesibles con barras de apoyo', 'Personal entrenado en atención inclusiva', 'Excursiones con transporte adaptado'],
    featuresEN: ['Adapted all-inclusive resorts', 'Amphibious chairs at premium resorts', 'Accessible rooms with grab bars', 'Staff trained in inclusive care', 'Excursions with adapted transport'],
    descriptionES: 'Punta Cana es ideal para viajeros con movilidad reducida que buscan resorts todo incluido con servicios accesibles en playas de arena blanca.',
    descriptionEN: 'Punta Cana is ideal for travelers with reduced mobility seeking all-inclusive resorts with accessible services on white sand beaches.',
    tags: ['caribe', 'playa', 'relax'],
  },
  {
    id: 'costa-rica',
    name: 'San José / Manuel Antonio',
    country: 'Costa Rica',
    flag: '🇨🇷',
    bgColor: 'bg-emerald-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'cognitiva'],
    featuresES: ['Parque Nacional Manuel Antonio accesible', 'Senderos adaptados en reservas', 'Hoteles eco accesibles certificados', 'Avistamiento de vida silvestre adaptado', 'Guías especializados en turismo inclusivo', 'Leyes fuertes de accesibilidad (Ley 7600)'],
    featuresEN: ['Accessible Manuel Antonio National Park', 'Adapted trails in reserves', 'Certified eco-accessible hotels', 'Adapted wildlife watching', 'Guides specialized in inclusive tourism', 'Strong accessibility laws (Law 7600)'],
    descriptionES: 'Costa Rica lidera el ecoturismo accesible en LATAM con la Ley 7600, parques nacionales adaptados y hoteles eco-accesibles certificados.',
    descriptionEN: 'Costa Rica leads accessible ecotourism in LATAM with Law 7600, adapted national parks, and certified eco-accessible hotels.',
    tags: ['naturaleza', 'ecoturismo', 'aventura'],
  },
  {
    id: 'panama',
    name: 'Ciudad de Panamá',
    country: 'Panamá',
    flag: '🇵🇦',
    bgColor: 'bg-red-400',
    accessibilityRating: 3,
    disabilityTypes: ['motriz', 'visual'],
    featuresES: ['Canal de Panamá con rampas y ascensores', 'Casco Viejo con recorridos adaptados', 'Metro accesible inaugurado 2014', 'Multiplaza con infraestructura completa', 'Tours al Canal con intérpretes LSP'],
    featuresEN: ['Panama Canal with ramps and elevators', 'Casco Viejo with adapted tours', 'Accessible metro opened 2014', 'Multiplaza with complete infrastructure', 'Canal tours with LSP interpreters'],
    descriptionES: 'Ciudad de Panamá ofrece metro accesible, tours adaptados al Canal y una infraestructura urbana moderna con buena cobertura de accesibilidad.',
    descriptionEN: 'Panama City offers accessible metro, adapted Canal tours, and modern urban infrastructure with good accessibility coverage.',
    tags: ['ciudad', 'cultura', 'historia'],
  },
  {
    id: 'lima',
    name: 'Lima',
    country: 'Perú',
    flag: '🇵🇪',
    bgColor: 'bg-orange-400',
    accessibilityRating: 3,
    disabilityTypes: ['motriz', 'visual', 'auditiva'],
    featuresES: ['Museo Larco con recorridos táctiles', 'Miraflores con malecón accesible', 'Restaurantes gastronómicos accesibles', 'Tours a Machu Picchu con asistencia', 'Aeropuerto Jorge Chávez certificado', 'Línea 1 del Metro accesible'],
    featuresEN: ['Larco Museum with tactile tours', 'Miraflores with accessible boardwalk', 'Accessible gourmet restaurants', 'Tours to Machu Picchu with assistance', 'Certified Jorge Chávez Airport', 'Accessible Metro Line 1'],
    descriptionES: 'Lima combina gastronomía de clase mundial con infraestructura accesible creciente en Miraflores. El Museo Larco ofrece recorridos táctiles únicos.',
    descriptionEN: 'Lima combines world-class gastronomy with growing accessible infrastructure in Miraflores. The Larco Museum offers unique tactile tours.',
    tags: ['gastronomia', 'cultura', 'ciudad'],
  },
  {
    id: 'bogota',
    name: 'Bogotá',
    country: 'Colombia',
    flag: '🇨🇴',
    bgColor: 'bg-indigo-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva'],
    featuresES: ['TransMilenio con estaciones accesibles', 'Museos con programas para sordociegos', 'Ciclovía dominical adaptada', 'Biblioteca Pública con materiales braille', 'Teatro con intérpretes LSC', 'Parque Simón Bolívar accesible'],
    featuresEN: ['TransMilenio with accessible stations', 'Museums with programs for deafblind', 'Accessible Sunday ciclovía', 'Public Library with braille materials', 'Theater with LSC interpreters', 'Accessible Simón Bolívar Park'],
    descriptionES: 'Bogotá tiene una de las políticas de accesibilidad más avanzadas de Colombia, con TransMilenio adaptado, museos inclusivos y ciclovía para todos.',
    descriptionEN: 'Bogotá has one of the most advanced accessibility policies in Colombia, with adapted TransMilenio, inclusive museums, and ciclovía for all.',
    tags: ['ciudad', 'cultura', 'naturaleza'],
  },
  {
    id: 'medellin',
    name: 'Medellín',
    country: 'Colombia',
    flag: '🇨🇴',
    bgColor: 'bg-purple-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'cognitiva', 'cronica_invisible'],
    featuresES: ['Metro + Metrocable con ascensores', 'Parques biblioteca accesibles', 'Jardín Botánico con rampas y braille', 'Programa "Medellín Accesible"', 'Clínicas de clase mundial', 'Clima primaveral ideal para movilidad reducida'],
    featuresEN: ['Metro + Metrocable with elevators', 'Accessible library parks', 'Botanical Garden with ramps and braille', '"Medellín Accesible" program', 'World-class clinics', 'Perpetual spring climate ideal for reduced mobility'],
    descriptionES: 'Medellín, la "Ciudad de la Eterna Primavera", combina innovación urbana accesible con el programa oficial "Medellín Accesible" y clima ideal.',
    descriptionEN: 'Medellín, the "City of Eternal Spring," combines accessible urban innovation with the official "Medellín Accesible" program and ideal climate.',
    tags: ['ciudad', 'cultura', 'naturaleza'],
  },
  {
    id: 'la-habana',
    name: 'La Habana',
    country: 'Cuba',
    flag: '🇨🇺',
    bgColor: 'bg-pink-400',
    accessibilityRating: 2,
    disabilityTypes: ['motriz', 'auditiva'],
    featuresES: ['Habana Vieja con calles adoquinadas (desafío)', 'Hotel Nacional con acceso adaptado', 'Tours privados en autos clásicos adaptados', 'Malecón relativamente plano', 'Personal de hoteles capacitado', 'Cuidado médico accesible de alta calidad'],
    featuresEN: ['Old Havana with cobblestone streets (challenge)', 'Hotel Nacional with adapted access', 'Private tours in adapted classic cars', 'Relatively flat Malecón', 'Trained hotel staff', 'Accessible high-quality medical care'],
    descriptionES: 'La Habana ofrece una experiencia única aunque con desafíos en accesibilidad por su arquitectura histórica. Los hoteles principales y tours privados son adaptados.',
    descriptionEN: 'Havana offers a unique experience though with accessibility challenges due to its historic architecture. Main hotels and private tours are adapted.',
    tags: ['cultura', 'historia', 'caribe'],
  },
]
