import type { DisabilityType } from '@/types/profile'

export interface Destination {
  id: string
  name: string
  country: string
  flag: string
  bgColor: string
  accessibilityRating: number // 1-5
  disabilityTypes: DisabilityType[] // which needs are well covered
  featuresES: string[]
  featuresEN: string[]
  descriptionES: string
  descriptionEN: string
  tags: string[]
}

export const DESTINATIONS: Destination[] = [
  {
    id: 'puerto-rico',
    name: 'San Juan',
    country: 'Puerto Rico',
    flag: '🇵🇷',
    bgColor: 'bg-blue-400',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva'],
    featuresES: ['Playas con sillas anfibias', 'Hoteles certificados ADA', 'Transporte adaptado', 'Señalización en braille', 'Guías en lengua de señas'],
    featuresEN: ['Beaches with amphibious chairs', 'ADA-certified hotels', 'Adapted transport', 'Braille signage', 'Sign language guides'],
    descriptionES: 'San Juan es uno de los destinos más accesibles del Caribe, con infraestructura ADA en hoteles, playas adaptadas y transporte público accesible.',
    descriptionEN: 'San Juan is one of the most accessible destinations in the Caribbean, with ADA infrastructure in hotels, adapted beaches, and accessible public transport.',
    tags: ['caribe', 'playa', 'cultura'],
  },
  {
    id: 'cancun',
    name: 'Cancún',
    country: 'México',
    flag: '🇲🇽',
    bgColor: 'bg-cyan-400',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual'],
    featuresES: ['Zona Hotelera con accesos adaptados', 'Playas accesibles en El Garrafón', 'Hoteles all-inclusive con sillas de ruedas', 'Rampas en zona arqueológica Tulum', 'Transporte turístico adaptado'],
    featuresEN: ['Hotel Zone with adapted access', 'Accessible beaches at El Garrafón', 'All-inclusive hotels with wheelchairs', 'Ramps at Tulum archaeological zone', 'Adapted tourist transport'],
    descriptionES: 'Cancún ofrece una zona hotelera con amplia infraestructura accesible, playas adaptadas y tours accesibles a zonas arqueológicas cercanas.',
    descriptionEN: 'Cancún offers a hotel zone with extensive accessible infrastructure, adapted beaches, and accessible tours to nearby archaeological sites.',
    tags: ['caribe', 'playa', 'naturaleza'],
  },
  {
    id: 'cartagena',
    name: 'Cartagena',
    country: 'Colombia',
    flag: '🇨🇴',
    bgColor: 'bg-yellow-400',
    accessibilityRating: 3,
    disabilityTypes: ['motriz', 'auditiva'],
    featuresES: ['Ciudad amurallada con rutas adaptadas', 'Hoteles boutique accesibles en el centro', 'Playas accesibles en Bocagrande', 'Audioguías disponibles', 'Carros de golf adaptados para tours'],
    featuresEN: ['Walled city with adapted routes', 'Accessible boutique hotels downtown', 'Accessible beaches in Bocagrande', 'Audio guides available', 'Adapted golf carts for tours'],
    descriptionES: 'Cartagena combina historia colonial con infraestructura accesible creciente. El centro histórico tiene rutas adaptadas y transporte en carros de golf.',
    descriptionEN: 'Cartagena combines colonial history with growing accessible infrastructure. The historic center has adapted routes and golf cart transport.',
    tags: ['cultura', 'historia', 'caribe'],
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    bgColor: 'bg-sky-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva'],
    featuresES: ['Metro con plataformas elevadoras', 'Museos con recorridos táctiles', 'Teatro Colón accesible', 'Semáforos con señal sonora', 'Guías en lengua de señas argentina (LSA)', 'Mapas en braille'],
    featuresEN: ['Subway with elevating platforms', 'Museums with tactile tours', 'Accessible Teatro Colón', 'Traffic lights with audio signals', 'Argentine sign language (LSA) guides', 'Braille maps'],
    descriptionES: 'Buenos Aires tiene una de las infraestructuras de accesibilidad más desarrolladas de LATAM, con metro adaptado, museos inclusivos y amplia red de apoyo.',
    descriptionEN: 'Buenos Aires has one of the most developed accessibility infrastructures in LATAM, with adapted subway, inclusive museums, and extensive support network.',
    tags: ['cultura', 'ciudad', 'gastronomia'],
  },
  {
    id: 'cdmx',
    name: 'Ciudad de México',
    country: 'México',
    flag: '🇲🇽',
    bgColor: 'bg-green-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'auditiva'],
    featuresES: ['Metro con módulos de accesibilidad', 'Museos con lenguaje de señas mexicano (LSM)', 'Paseo de la Reforma con rampas', 'TURIBUS accesible', 'Zonas arqueológicas con recorridos adaptados', 'Braille en museos INAH'],
    featuresEN: ['Subway with accessibility modules', 'Museums with Mexican sign language (LSM)', 'Paseo de la Reforma with ramps', 'Accessible TURIBUS', 'Archaeological zones with adapted tours', 'Braille in INAH museums'],
    descriptionES: 'La CDMX cuenta con infraestructura de accesibilidad en transporte público, museos de clase mundial con programas inclusivos y tours adaptados.',
    descriptionEN: 'Mexico City has accessibility infrastructure in public transport, world-class museums with inclusive programs, and adapted tours.',
    tags: ['cultura', 'ciudad', 'historia', 'gastronomia'],
  },
  {
    id: 'punta-cana',
    name: 'Punta Cana',
    country: 'República Dominicana',
    flag: '🇩🇴',
    bgColor: 'bg-amber-400',
    accessibilityRating: 3,
    disabilityTypes: ['motriz'],
    featuresES: ['Resorts all-inclusive adaptados', 'Sillas anfibias en resorts premium', 'Habitaciones accesibles con barras de apoyo', 'Personal entrenado en atención inclusiva', 'Excursiones con transporte adaptado'],
    featuresEN: ['Adapted all-inclusive resorts', 'Amphibious chairs at premium resorts', 'Accessible rooms with grab bars', 'Staff trained in inclusive care', 'Excursions with adapted transport'],
    descriptionES: 'Punta Cana es ideal para viajeros con movilidad reducida que buscan resorts todo incluido con servicios accesibles en playas de arena blanca.',
    descriptionEN: 'Punta Cana is ideal for travelers with reduced mobility seeking all-inclusive resorts with accessible services on white sand beaches.',
    tags: ['caribe', 'playa', 'relax'],
  },
  {
    id: 'costa-rica',
    name: 'San José / Manuel Antonio',
    country: 'Costa Rica',
    flag: '🇨🇷',
    bgColor: 'bg-emerald-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'cognitiva'],
    featuresES: ['Parque Nacional Manuel Antonio accesible', 'Senderos adaptados en reservas', 'Hoteles eco accesibles certificados', 'Avistamiento de vida silvestre adaptado', 'Guías especializados en turismo inclusivo', 'Leyes fuertes de accesibilidad (Ley 7600)'],
    featuresEN: ['Accessible Manuel Antonio National Park', 'Adapted trails in reserves', 'Certified eco-accessible hotels', 'Adapted wildlife watching', 'Guides specialized in inclusive tourism', 'Strong accessibility laws (Law 7600)'],
    descriptionES: 'Costa Rica lidera el ecoturismo accesible en LATAM con la Ley 7600, parques nacionales adaptados y hoteles eco-accesibles certificados.',
    descriptionEN: 'Costa Rica leads accessible ecotourism in LATAM with Law 7600, adapted national parks, and certified eco-accessible hotels.',
    tags: ['naturaleza', 'ecoturismo', 'aventura'],
  },
  {
    id: 'panama',
    name: 'Ciudad de Panamá',
    country: 'Panamá',
    flag: '🇵🇦',
    bgColor: 'bg-red-400',
    accessibilityRating: 3,
    disabilityTypes: ['motriz', 'visual'],
    featuresES: ['Canal de Panamá con rampas y ascensores', 'Casco Viejo con recorridos adaptados', 'Metro accesible inaugurado 2014', 'Multiplaza con infraestructura completa', 'Tours al Canal con intérpretes LSP'],
    featuresEN: ['Panama Canal with ramps and elevators', 'Casco Viejo with adapted tours', 'Accessible metro opened 2014', 'Multiplaza with complete infrastructure', 'Canal tours with LSP interpreters'],
    descriptionES: 'Ciudad de Panamá ofrece metro accesible, tours adaptados al Canal y una infraestructura urbana moderna con buena cobertura de accesibilidad.',
    descriptionEN: 'Panama City offers accessible metro, adapted Canal tours, and modern urban infrastructure with good accessibility coverage.',
    tags: ['ciudad', 'cultura', 'historia'],
  },
  {
    id: 'lima',
    name: 'Lima',
    country: 'Perú',
    flag: '🇵🇪',
    bgColor: 'bg-orange-400',
    accessibilityRating: 3,
    disabilityTypes: ['motriz', 'visual', 'auditiva'],
    featuresES: ['Museo Larco con recorridos táctiles', 'Miraflores con malecón accesible', 'Restaurantes gastronómicos accesibles', 'Tours a Machu Picchu con asistencia', 'Aeropuerto Jorge Chávez certificado', 'Línea 1 del Metro accesible'],
    featuresEN: ['Larco Museum with tactile tours', 'Miraflores with accessible boardwalk', 'Accessible gourmet restaurants', 'Tours to Machu Picchu with assistance', 'Certified Jorge Chávez Airport', 'Accessible Metro Line 1'],
    descriptionES: 'Lima combina gastronomía de clase mundial con infraestructura accesible creciente en Miraflores. El Museo Larco ofrece recorridos táctiles únicos.',
    descriptionEN: 'Lima combines world-class gastronomy with growing accessible infrastructure in Miraflores. The Larco Museum offers unique tactile tours.',
    tags: ['gastronomia', 'cultura', 'ciudad'],
  },
  {
    id: 'bogota',
    name: 'Bogotá',
    country: 'Colombia',
    flag: '🇨🇴',
    bgColor: 'bg-indigo-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva'],
    featuresES: ['TransMilenio con estaciones accesibles', 'Museos con programas para sordociegos', 'Ciclovía dominical adaptada', 'Biblioteca Pública con materiales braille', 'Teatro con intérpretes LSC', 'Parque Simón Bolívar accesible'],
    featuresEN: ['TransMilenio with accessible stations', 'Museums with programs for deafblind', 'Accessible Sunday ciclovía', 'Public Library with braille materials', 'Theater with LSC interpreters', 'Accessible Simón Bolívar Park'],
    descriptionES: 'Bogotá tiene una de las políticas de accesibilidad más avanzadas de Colombia, con TransMilenio adaptado, museos inclusivos y ciclovía para todos.',
    descriptionEN: 'Bogotá has one of the most advanced accessibility policies in Colombia, with adapted TransMilenio, inclusive museums, and ciclovía for all.',
    tags: ['ciudad', 'cultura', 'naturaleza'],
  },
  {
    id: 'medellin',
    name: 'Medellín',
    country: 'Colombia',
    flag: '🇨🇴',
    bgColor: 'bg-purple-500',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'cognitiva', 'cronica_invisible'],
    featuresES: ['Metro + Metrocable con ascensores', 'Parques biblioteca accesibles', 'Jardín Botánico con rampas y braille', 'Programa "Medellín Accesible"', 'Clínicas de clase mundial', 'Clima primaveral ideal para movilidad reducida'],
    featuresEN: ['Metro + Metrocable with elevators', 'Accessible library parks', 'Botanical Garden with ramps and braille', '"Medellín Accesible" program', 'World-class clinics', 'Perpetual spring climate ideal for reduced mobility'],
    descriptionES: 'Medellín, la "Ciudad de la Eterna Primavera", combina innovación urbana accesible con el programa oficial "Medellín Accesible" y clima ideal.',
    descriptionEN: 'Medellín, the "City of Eternal Spring," combines accessible urban innovation with the official "Medellín Accesible" program and ideal climate.',
    tags: ['ciudad', 'cultura', 'naturaleza'],
  },
  {
    id: 'la-habana',
    name: 'La Habana',
    country: 'Cuba',
    flag: '🇨🇺',
    bgColor: 'bg-pink-400',
    accessibilityRating: 2,
    disabilityTypes: ['motriz', 'auditiva'],
    featuresES: ['Habana Vieja con calles adoquinadas (desafío)', 'Hotel Nacional con acceso adaptado', 'Tours privados en autos clásicos adaptados', 'Malecón relativamente plano', 'Personal de hoteles capacitado', 'Cuidado médico accesible de alta calidad'],
    featuresEN: ['Old Havana with cobblestone streets (challenge)', 'Hotel Nacional with adapted access', 'Private tours in adapted classic cars', 'Relatively flat Malecón', 'Trained hotel staff', 'Accessible high-quality medical care'],
    descriptionES: 'La Habana ofrece una experiencia única aunque con desafíos en accesibilidad por su arquitectura histórica. Los hoteles principales y tours privados son adaptados.',
    descriptionEN: 'Havana offers a unique experience though with accessibility challenges due to its historic architecture. Main hotels and private tours are adapted.',
    tags: ['cultura', 'historia', 'caribe'],
  },

  // EE.UU. y Canadá
  {
    id: 'nueva-york',
    name: 'Nueva York',
    country: 'EE.UU.',
    flag: '🇺🇸',
    bgColor: 'bg-slate-600',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva'],
    featuresES: ['ADA en todos los espacios públicos y edificios federales', 'Taxis y Uber con opción WAV (vehículo accesible en silla de ruedas)', 'Metropolitan Museum con tours táctiles y en lengua de señas (ASL)', 'Broadway con funciones con subtítulos y audiodescripción', 'Estatua de la Libertad con acceso en silla de ruedas al pedestal', 'MTA Subway con ascensores (cobertura parcial ~25% estaciones)', 'Central Park con rutas pavimentadas accesibles'],
    featuresEN: ['ADA in all public spaces and federal buildings', 'Taxis and Uber with WAV option (wheelchair accessible vehicle)', 'Metropolitan Museum with tactile tours and ASL', 'Broadway with captioned and audio-described performances', 'Statue of Liberty with wheelchair access to pedestal', 'MTA Subway with elevators (partial coverage ~25% stations)', 'Central Park with accessible paved routes'],
    descriptionES: 'Nueva York lidera en legislación ADA y diversidad de servicios accesibles. Broadway, museos de clase mundial y transporte adaptado conviven con un metro histórico de cobertura parcial.',
    descriptionEN: 'New York leads in ADA legislation and diversity of accessible services. Broadway, world-class museums, and adapted transport coexist with a historic subway of partial coverage.',
    tags: ['eeuu', 'cultura', 'ciudad', 'historia'],
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    country: 'EE.UU.',
    flag: '🇺🇸',
    bgColor: 'bg-orange-600',
    accessibilityRating: 4,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cronica_invisible'],
    featuresES: ['BART y Muni Metro 100% accesibles con ascensores', 'Alcatraz con audio tour accesible y ferry adaptado', 'Golden Gate Park con rutas pavimentadas para sillas de ruedas', 'Fisherman\'s Wharf con paseos costeros accesibles', 'Clemente Disability Resource Center activo', 'Hoteles con certificación ADA extendida', 'Cable cars históricos con plataformas de embarque adaptadas'],
    featuresEN: ['BART and Muni Metro 100% accessible with elevators', 'Alcatraz with accessible audio tour and adapted ferry', 'Golden Gate Park with paved wheelchair routes', "Fisherman's Wharf with accessible coastal walks", 'Active Clemente Disability Resource Center', 'Hotels with extended ADA certification', 'Historic cable cars with adapted boarding platforms'],
    descriptionES: 'San Francisco combina transporte público accesible de primer nivel con atracciones icónicas adaptadas. Sus colinas empinadas son un reto, pero el BART y Muni ofrecen cobertura completa.',
    descriptionEN: 'San Francisco combines top-tier accessible public transport with adapted iconic attractions. Its steep hills are a challenge, but BART and Muni offer full coverage.',
    tags: ['eeuu', 'ciudad', 'naturaleza', 'cultura'],
  },
  {
    id: 'orlando',
    name: 'Orlando',
    country: 'EE.UU.',
    flag: '🇺🇸',
    bgColor: 'bg-violet-500',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'autismo', 'cognitiva', 'cronica_invisible'],
    featuresES: ['Walt Disney World — líder mundial en accesibilidad para parques temáticos', 'Disability Access Service (DAS) en todos los parques Disney y Universal', 'Universal Studios con Attraction Assistance Pass', 'SeaWorld con programas para personas con autismo (certificado IBCCES)', 'Hotel Disney con habitaciones totalmente accesibles y servicios médicos', 'Transporte gratuito accesible entre parques Disney', 'Quiet Hours en parques para viajeros con sensibilidad sensorial'],
    featuresEN: ['Walt Disney World — world leader in theme park accessibility', 'Disability Access Service (DAS) at all Disney and Universal parks', 'Universal Studios with Attraction Assistance Pass', 'SeaWorld with autism programs (IBCCES certified)', 'Disney hotels with fully accessible rooms and medical services', 'Free accessible transport between Disney parks', 'Quiet Hours at parks for sensory-sensitive travelers'],
    descriptionES: 'Orlando es el destino más accesible para parques temáticos en el mundo. Disney, Universal y SeaWorld tienen programas líderes para todo tipo de discapacidad, incluyendo autismo y necesidades sensoriales.',
    descriptionEN: 'Orlando is the most accessible theme park destination in the world. Disney, Universal, and SeaWorld have leading programs for all types of disability, including autism and sensory needs.',
    tags: ['eeuu', 'familia', 'relax', 'ciudad'],
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canadá',
    flag: '🇨🇦',
    bgColor: 'bg-red-700',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva', 'cronica_invisible'],
    featuresES: ['TTC (metro y autobús) 100% accesible con elevadores Wheel-Trans', 'Museos Royal Ontario y Art Gallery con programas de accesibilidad total', 'CN Tower con ascensores accesibles y restaurante adaptado', 'Ripley\'s Aquarium con recorridos para sordos y ciegos', 'Código de Derechos Humanos de Ontario — protección legal robusta', 'Programa municipal "Toronto Accessibility" con mapas detallados', 'Hoteles con certificación AccessNow verificada'],
    featuresEN: ['TTC (subway and bus) 100% accessible with Wheel-Trans elevators', 'Royal Ontario Museum and Art Gallery with full accessibility programs', 'CN Tower with accessible elevators and adapted restaurant', "Ripley's Aquarium with tours for deaf and blind visitors", 'Ontario Human Rights Code — robust legal protection', 'Municipal "Toronto Accessibility" program with detailed maps', 'Hotels with verified AccessNow certification'],
    descriptionES: 'Toronto es consistentemente clasificada entre las ciudades más accesibles de América del Norte. Su legislación robusta, transporte 100% adaptado y multiculturalismo la hacen destino de referencia.',
    descriptionEN: 'Toronto is consistently ranked among the most accessible cities in North America. Its robust legislation, 100% adapted transport, and multiculturalism make it a reference destination.',
    tags: ['canada', 'ciudad', 'cultura', 'naturaleza'],
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canadá',
    flag: '🇨🇦',
    bgColor: 'bg-green-600',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva', 'cronica_invisible'],
    featuresES: ['SkyTrain y autobuses TransLink totalmente accesibles', 'Stanley Park con rutas pavimentadas de 8.8 km accesibles en silla de ruedas', 'Vancouver Aquarium con programas para autismo y sordoceguera', 'Granville Island completamente accesible con mercado adaptado', 'Legislación BC Human Rights Code aplicada estrictamente', 'Ski Whistler con programa de esquí adaptado (Whistler Adaptive)', 'App "Access Vancouver" con guía de movilidad en tiempo real'],
    featuresEN: ['SkyTrain and TransLink buses fully accessible', 'Stanley Park with 8.8 km of wheelchair-accessible paved routes', 'Vancouver Aquarium with autism and deafblind programs', 'Granville Island fully accessible with adapted market', 'BC Human Rights Code strictly enforced', 'Whistler ski with adapted ski program (Whistler Adaptive)', '"Access Vancouver" app with real-time mobility guide'],
    descriptionES: 'Vancouver combina naturaleza espectacular con infraestructura de accesibilidad de primer nivel. Stanley Park, transporte 100% adaptado y el programa de esquí accesible en Whistler la hacen única.',
    descriptionEN: 'Vancouver combines spectacular nature with world-class accessibility infrastructure. Stanley Park, 100% adapted transport, and the Whistler Adaptive ski program make it unique.',
    tags: ['canada', 'naturaleza', 'ciudad', 'aventura'],
  },

  // Europa y Asia-Pacífico
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'España',
    flag: '🇪🇸',
    bgColor: 'bg-red-500',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva'],
    featuresES: ['Metro 100% accesible con ascensores en todas las estaciones', 'Playa de la Barceloneta con sillas anfibias gratuitas', 'Sagrada Família con audioguías y recorridos táctiles', 'Autobuses de piso bajo en toda la red', 'Museos con lengua de signos española (LSE)', 'App "BCN Accessible" con rutas adaptadas', 'Ramblas con carril accesible señalizado'],
    featuresEN: ['100% accessible metro with elevators at all stations', 'Barceloneta beach with free amphibious chairs', 'Sagrada Família with audio guides and tactile tours', 'Low-floor buses across the entire network', 'Museums with Spanish sign language (LSE)', '"BCN Accessible" app with adapted routes', 'Las Ramblas with marked accessible lane'],
    descriptionES: 'Barcelona es referente mundial en turismo accesible. Su metro completamente adaptado, playas con sillas anfibias gratuitas y la mayoría de atracciones con acceso inclusivo la convierten en destino ideal.',
    descriptionEN: 'Barcelona is a world reference in accessible tourism. Its fully adapted metro, beaches with free amphibious chairs, and most attractions with inclusive access make it an ideal destination.',
    tags: ['europa', 'cultura', 'playa', 'ciudad'],
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Países Bajos',
    flag: '🇳🇱',
    bgColor: 'bg-orange-500',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva', 'cronica_invisible'],
    featuresES: ['Tranvías y metros totalmente accesibles (GVB)', 'Rijksmuseum con recorridos táctiles y LSB', 'Barcos-canal adaptados para sillas de ruedas', 'Anne Frank Huis con tour virtual accesible', 'Hoteles con certificación AccessibleNL', 'Calles planas y pavimento uniforme', 'Sistema nacional de información de accesibilidad (ANWB)'],
    featuresEN: ['Fully accessible trams and metro (GVB)', 'Rijksmuseum with tactile tours and Dutch SL', 'Wheelchair-adapted canal boats', 'Anne Frank House with accessible virtual tour', 'Hotels with AccessibleNL certification', 'Flat streets and uniform pavement', 'National accessibility information system (ANWB)'],
    descriptionES: 'Amsterdam es consistentemente clasificada entre las ciudades más accesibles de Europa. Su terreno plano, transporte adaptado y cultura de inclusión la hacen excepcionalmente amigable.',
    descriptionEN: 'Amsterdam is consistently ranked among the most accessible cities in Europe. Its flat terrain, adapted transport, and culture of inclusion make it exceptionally friendly.',
    tags: ['europa', 'cultura', 'ciudad', 'historia'],
  },
  {
    id: 'berlin',
    name: 'Berlín',
    country: 'Alemania',
    flag: '🇩🇪',
    bgColor: 'bg-gray-700',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva'],
    featuresES: ['U-Bahn y S-Bahn con 95% de estaciones accesibles', 'Museo Judío con audioguías y recorridos táctiles', 'Semáforos con señal sonora y vibrotáctil en toda la ciudad', 'Línea de pavimento táctil en aceras', 'Filarmónica de Berlín con bucle de inducción auditiva', 'Puerta de Brandenburgo con rampas y plataformas', 'BVG app con información de accesibilidad en tiempo real'],
    featuresEN: ['U-Bahn and S-Bahn with 95% accessible stations', 'Jewish Museum with audio guides and tactile tours', 'Traffic lights with audio and vibrotactile signals citywide', 'Tactile paving line on sidewalks', 'Berlin Philharmonic with hearing induction loop', 'Brandenburg Gate with ramps and platforms', 'BVG app with real-time accessibility information'],
    descriptionES: 'Berlín lidera en accesibilidad urbana en Europa. Su red de transporte casi completamente adaptada, señalización táctil y programas de inclusión cultural la convierten en referencia global.',
    descriptionEN: 'Berlin leads in urban accessibility in Europe. Its near-completely adapted transport network, tactile signage, and cultural inclusion programs make it a global reference.',
    tags: ['europa', 'cultura', 'historia', 'ciudad'],
  },
  {
    id: 'paris',
    name: 'París',
    country: 'Francia',
    flag: '🇫🇷',
    bgColor: 'bg-blue-600',
    accessibilityRating: 3,
    disabilityTypes: ['motriz', 'visual', 'auditiva'],
    featuresES: ['Torre Eiffel con ascensores accesibles hasta el 2° piso', 'Museo de Orsay con recorridos táctiles gratuitos', 'RER y líneas de metro parcialmente accesibles (líneas A, B, 14)', 'Louvre con entrada gratuita para personas con discapacidad + acompañante', 'Autobuses de piso bajo en toda la red', 'Versalles con sillas de ruedas gratuitas disponibles', 'Guías de accesibilidad por arrondissement'],
    featuresEN: ['Eiffel Tower with accessible elevators to 2nd floor', "Musée d'Orsay with free tactile tours", 'RER and partial metro access (lines A, B, 14)', 'Louvre with free entry for people with disabilities + companion', 'Low-floor buses across the network', 'Versailles with free wheelchairs available', 'Accessibility guides by arrondissement'],
    descriptionES: 'París ofrece experiencias culturales de clase mundial adaptadas, aunque el metro histórico tiene cobertura parcial. La mayoría de museos son plenamente accesibles y gratuitos para personas con discapacidad.',
    descriptionEN: 'Paris offers world-class adapted cultural experiences, though the historic metro has partial coverage. Most museums are fully accessible and free for people with disabilities.',
    tags: ['europa', 'cultura', 'historia', 'gastronomia'],
  },
  {
    id: 'tokio',
    name: 'Tokio',
    country: 'Japón',
    flag: '🇯🇵',
    bgColor: 'bg-rose-500',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva'],
    featuresES: ['Red de metro con ascensores en todas las salidas principales', 'Pavimento táctil Tenji-block en toda la ciudad desde 1967', 'Señalización sonora en semáforos y estaciones', 'Inodoros accesibles de alta tecnología en espacios públicos', 'Shinkansen con espacios para sillas de ruedas reservables', 'Guías de accesibilidad en inglés en cada atracción', 'Personal de estaciones entrenado en asistencia a personas con discapacidad'],
    featuresEN: ['Metro network with elevators at all major exits', 'Tenji-block tactile paving citywide since 1967', 'Audible signals at traffic lights and stations', 'High-tech accessible toilets in public spaces', 'Shinkansen with bookable wheelchair spaces', 'English accessibility guides at every attraction', 'Station staff trained to assist people with disabilities'],
    descriptionES: 'Tokio es considerada la ciudad más accesible de Asia. Su sistema de pavimento táctil pionero, metro completamente adaptado y cultura de servicio excepcional la hacen destino de primer nivel.',
    descriptionEN: 'Tokyo is considered the most accessible city in Asia. Its pioneering tactile paving system, fully adapted metro, and exceptional service culture make it a top-tier destination.',
    tags: ['asia', 'cultura', 'gastronomia', 'ciudad'],
  },
  {
    id: 'singapur',
    name: 'Singapur',
    country: 'Singapur',
    flag: '🇸🇬',
    bgColor: 'bg-red-600',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva', 'cronica_invisible'],
    featuresES: ['MRT 100% accesible con ascensores en todas las estaciones', 'Gardens by the Bay con senderos totalmente accesibles', 'Programa "Enabling Village" — centro de recursos para discapacidad', 'Taxis y Grab con opción de vehículo accesible', 'Marina Bay Sands con habitaciones y casino accesibles', 'Hawker Centers con mesas adaptadas', 'App "AccessAble Singapore" con mapa de accesibilidad detallado'],
    featuresEN: ['100% accessible MRT with elevators at all stations', 'Gardens by the Bay with fully accessible pathways', '"Enabling Village" program — disability resource center', 'Taxis and Grab with accessible vehicle option', 'Marina Bay Sands with accessible rooms and casino', 'Hawker Centers with adapted tables', '"AccessAble Singapore" app with detailed accessibility map'],
    descriptionES: 'Singapur es el destino más accesible de Asia según múltiples rankings. Su infraestructura de primer nivel, transporte 100% adaptado y políticas de inclusión social la hacen excepcionalmente inclusiva.',
    descriptionEN: 'Singapore is the most accessible destination in Asia according to multiple rankings. Its world-class infrastructure, 100% adapted transport, and social inclusion policies make it exceptionally inclusive.',
    tags: ['asia', 'ciudad', 'gastronomia', 'naturaleza'],
  },
  {
    id: 'sydney',
    name: 'Sídney',
    country: 'Australia',
    flag: '🇦🇺',
    bgColor: 'bg-teal-600',
    accessibilityRating: 5,
    disabilityTypes: ['motriz', 'visual', 'auditiva', 'cognitiva', 'cronica_invisible'],
    featuresES: ['Ópera de Sídney con tours accesibles y bucle de inducción', 'Playas accesibles con sillas anfibias y rampas de arena (Bondi, Manly)', 'Tren, ferry y autobús totalmente accesibles (Transport for NSW)', 'Jardín Botánico con senderos pavimentados y braille', 'Acuario de Sídney con recorridos para personas con autismo', 'Disability Discrimination Act 1992 rigurosamente aplicada', 'App "Sydney Accessibility" con planificador de rutas inclusivas'],
    featuresEN: ['Sydney Opera House with accessible tours and induction loop', 'Accessible beaches with amphibious chairs and sand ramps (Bondi, Manly)', 'Fully accessible train, ferry and bus (Transport for NSW)', 'Botanic Garden with paved paths and braille', 'Sydney Aquarium with autism-friendly tours', 'Rigorously enforced Disability Discrimination Act 1992', '"Sydney Accessibility" app with inclusive route planner'],
    descriptionES: 'Sídney combina infraestructura de accesibilidad de primer nivel con entornos naturales espectaculares. Sus playas adaptadas, transporte inclusivo y legislación fuerte la posicionan como destino de excelencia.',
    descriptionEN: 'Sydney combines world-class accessibility infrastructure with spectacular natural environments. Its adapted beaches, inclusive transport, and strong legislation position it as a destination of excellence.',
    tags: ['oceania', 'playa', 'naturaleza', 'ciudad', 'cultura'],
  },
]
